# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactRedisPubSub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactRedisPubSub
  pod "PSSRedisClient"


  target 'ReactRedisPubSub-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactRedisPubSubTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

